#!/bin/sh
# Regenerates src/PipeWire.NET/Native/Generated from the external/pipewire
# submodule headers via ClangSharpPInvokeGenerator (a local dotnet tool, see
# .config/dotnet-tools.json). Run from the repository root:
#
#   dotnet tool restore
#   sh eng/generate.sh
set -eu
cd "$(dirname "$0")/.."

mkdir -p eng/include/pipewire

# meson generates pipewire/version.h from version.h.in; the generator needs it
# on the include path. Keep these numbers in sync with the submodule's
# meson.version and Directory.Build.props <Version>.
sed -e 's/@PIPEWIRE_VERSION_MAJOR@/1/g' \
    -e 's/@PIPEWIRE_VERSION_MINOR@/6/g' \
    -e 's/@PIPEWIRE_VERSION_MICRO@/8/g' \
    -e 's/@PIPEWIRE_API_VERSION@/"0.3"/g' \
    external/pipewire/src/pipewire/version.h.in > eng/include/pipewire/version.h

# One umbrella translation unit. Every header must be reached from a single
# --file: ClangSharp appends to the method class file per input, so passing
# several headers duplicates every shared declaration. pipewire.h pulls in the
# client API and the SPA types it references; the param headers below are not
# on that path but hold the enums and info structs the wrapper needs
# (formats, props, buffers, latency, routes, profiles).
cat > eng/include/pipewire-dotnet.h <<'HEADER'
/* Generated by eng/generate.sh. The single translation unit ClangSharp reads. */
#include <pipewire/pipewire.h>
#include <pipewire/extensions/metadata.h>
#include <spa/control/control.h>
#include <spa/param/audio/format.h>
#include <spa/param/audio/layout.h>
#include <spa/param/buffers.h>
#include <spa/param/format.h>
#include <spa/param/latency.h>
#include <spa/param/port-config.h>
#include <spa/param/profile.h>
#include <spa/param/props.h>
#include <spa/param/route.h>
#include <spa/param/tag.h>
#include <spa/param/video/format.h>
HEADER

rm -rf src/PipeWire.NET/Native/Generated
mkdir -p src/PipeWire.NET/Native/Generated

# The bundled libclang needs clang's builtin headers (stddef.h etc.); use the
# system clang's resource directory.
RESOURCE_DIR="$(clang -print-resource-dir)"

# --traverse only matches exact file paths, so the header set is expanded here
# rather than pinned in the rsp; a submodule bump then picks up new headers
# without editing this list. Only declarations actually reachable from the
# umbrella header are emitted, so listing every header is harmless.
find external/pipewire/src/pipewire external/pipewire/spa/include/spa eng/include \
    -name '*.h' -printf '--traverse\n%p\n' > eng/traverse.rsp

# The generator's exit code is its diagnostic (warning) count, so a successful
# run with warnings is nonzero; presence of the output files is checked instead.
dotnet tool run ClangSharpPInvokeGenerator -- --resource-directory "$RESOURCE_DIR" "@eng/pipewire.rsp" "@eng/traverse.rsp" || true
rm -f eng/traverse.rsp

test -f src/PipeWire.NET/Native/Generated/Pipewire.cs

# Fixups for macro bindings ClangSharp emits but C# cannot compile. If a
# submodule bump introduces new ones, extend this block, don't edit generated
# files. (Function bodies need no fixups: funcs-with-body=false keeps the
# static inline layer out entirely -- see the note in the rsp.)
#
# - INT64_MIN comes through as an nint-typed expression, which is not a valid
#   const initializer for a long.
sed -i 's/^\(    public const long SPA_TIME_INVALID = \).*$/\1long.MinValue;/' src/PipeWire.NET/Native/Generated/Pipewire.cs

# - PW_DIRECTION_* alias enum members, which do not implicitly convert to the
#   int the macro binding is typed as.
sed -i 's/^\(    public const int PW_DIRECTION_\(INPUT\|OUTPUT\) = \)SPA_DIRECTION_/\1(int)SPA_DIRECTION_/' src/PipeWire.NET/Native/Generated/Pipewire.cs

# - va_list (spa_log's *v methods, pw_log_logv) surfaces as a pointer to the
#   undefined __va_list_tag; treat it as an opaque pointer.
sed -i 's/__va_list_tag\*/void*/g; s/struct __va_list_tag \*/void */g' src/PipeWire.NET/Native/Generated/*.cs
