/* Generated by eng/generate.sh. The single translation unit ClangSharp reads. */
#include <pipewire/pipewire.h>
#include <pipewire/extensions/metadata.h>
#include <pipewire/impl-module.h>
#include <spa/control/control.h>
#include <spa/param/audio/format.h>
#include <spa/param/audio/layout.h>
#include <spa/param/buffers.h>
#include <spa/param/format.h>
#include <spa/param/latency.h>
#include <spa/param/port-config.h>
#include <spa/param/profile.h>
#include <spa/param/props.h>
#include <spa/param/route.h>
#include <spa/param/tag.h>
#include <spa/param/video/format.h>
